language: java

jdk:
  - oraclejdk8

#cache:
#  directories:
#  - $HOME/.m2
  
install:
    - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q

notifications:
      slack: openbase-org:$SLACK_ACCESS_TOCKEN

#before_install:
#  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
#  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

#deploy:
#  - provider: script
#    script: .travis/deploy.sh
#    on:
#        repo: openbase/openhab-binding-rsb
#        branch: master
#        jdk: oraclejdk8
#  - provider: script
#    script: .travis/deploy.sh
#    on:
#        repo: openbase/openhab-binding-rsb
#        tags: true
#        jdk: oraclejdk8
