language: java

branches:
  except:
      #- /^(?i:feature)-.*$/
      #- /^(?i:release)-.*$/

jdk:
  - oraclejdk8
  
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -q

notifications:
    email:
        on_success: never
        on_failure: change
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#bco

#before_install:
#  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
#  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

#deploy:
#  - provider: script
#    script: .travis/deploy.sh
#    on:
#        repo: openbase/openhab-binding-rsb
#        branch: master
#        jdk: oraclejdk8
#  - provider: script
#    script: .travis/deploy.sh
#    on:
#        repo: openbase/openhab-binding-rsb
#        tags: true
#        jdk: oraclejdk8
